version: '3.7'
services:
  postgres:
    build:
      context: ./postgres/
    networks:
      - hotel-network

  pgadmin:
    image: dpage/pgadmin4

    environment:
      - PGADMIN_DEFAULT_EMAIL=test@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_SERVER_JSON_FILE=/servers/servers.json

    volumes:
      - /./pgadmin4/servers/

    ports:
      - "8181:80"
    depends_on:
      - postgres
    networks:
      - hotel-network

  api:
    build:
      context: .

    ports:
      - "8000:8000"
    networks:
      - hotel-network

networks:
  hotel-network:
    driver: bridge
